openapi: 3.1.0

info:
  title: RTI Tracker API contract
  description: |
    API for managing RTI application functionalities.
    All endpoints are protected via opaque bearer token authentication.
  version: 1.0.0
  license:
    name: |
      Apache License
      Version 2.0, January 2004
    url: http://www.apache.org/licenses/

servers:
  - url: http://127.0.0.1:8080/api/v1
    description: Local development server

security:
  - opaqueBearerToken: []

paths:
  /rti-templates:
    $ref: "./paths/rti-templates.yaml#/~1rti-templates"
  /rti-templates/{id}:
    $ref: "./paths/rti-templates.yaml#/~1rti-templates~1{id}"
  /institutions:
    $ref: "./paths/institutions.yaml#/~1institutions"
  /institution/{id}:
    $ref: "./paths/institutions.yaml#/~1institution~1{id}"

components:
  securitySchemes:
    opaqueBearerToken:
      $ref: "./components/securitySchemes/security.yaml#/opaqueBearerToken"
  schemas:
    RTITemplateRequest:
      $ref: "./components/schemas/RTITemplates.yaml#/RTITemplateRequest"
    RTITemplateResponse:
      $ref: "./components/schemas/RTITemplates.yaml#/RTITemplateResponse"
    RTITemplateListResponse:
      $ref: "./components/schemas/RTITemplates.yaml#/RTITemplateListResponse"
    InstitutionRequest:
      $ref: "./components/schemas/institutions.yaml#/InstitutionRequest"
    InstitutionResponse:
      $ref: "./components/schemas/institutions.yaml#/InstitutionResponse"
    InstitutionsListResponse:
      $ref: "./components/schemas/institutions.yaml#/InstitutionsListResponse"
    Pagination:
      $ref: "./components/schemas/common.yaml#/Pagination"
    ErrorResponse:
      $ref: "./components/schemas/common.yaml#/ErrorResponse"
  responses:
    Unauthorized:
      $ref: "./components/responses/Errors.yaml#/Unauthorized"
    NotFound:
      $ref: "./components/responses/Errors.yaml#/NotFound"
    UnprocessableEntity:
      $ref: "./components/responses/Errors.yaml#/UnprocessableEntity"
    Conflict:
      $ref: "./components/responses/Errors.yaml#/Conflict"
    InternalServerError:
      $ref: "./components/responses/Errors.yaml#/InternalServerError"
  parameters:
    ObjectId:
      $ref: "./components/parameters/common.yaml#/ObjectId"
    PageParam:
      $ref: "./components/parameters/Pagination.yaml#/PageParam"
    PageSizeParam:
      $ref: "./components/parameters/Pagination.yaml#/PageSizeParam"
